# Generated by Django 5.1.3 on 2024-11-15 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_corretor_desafio_participacaodesafio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corretor',
            name='nome',
        ),
        migrations.AddField(
            model_name='corretor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corretor', to=settings.AUTH_USER_MODEL),
        ),
    ]
