# Generated by Django 5.1.3 on 2024-11-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_corretor_options_alter_desafio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='banner',
            field=models.ImageField(upload_to='public/base/banners/', verbose_name='Banner'),
        ),
    ]
