# Generated by Django 5.1.3 on 2024-11-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_desafio_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='banner',
            field=models.ImageField(upload_to='mysite/base/static/base/images/public', verbose_name='Banner'),
        ),
    ]
