services:
  django:
    container_name: django-portal
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"

#  nginx:
#    container_name: nginx-portal
#    image: nginx:1.27.0
#    volumes:
#      - ./staticfiles/static:/usr/share/nginx/html/static
#      - ./mediafiles:/usr/share/nginx/html/mediafiles
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - "80:80"
#    networks:
#      - custom_network
#    depends_on:
#      - django
#
  database:
    container_name: postgres-portal
    image: postgres:16.3
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
