services:
  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ../:/app:z
    env_file:
      - ../.env
    command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: always
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:1.27.0
    volumes:
      - ./staticfiles/static:/usr/share/nginx/html/static
      - ./mediafiles:/usr/share/nginx/html/mediafiles
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  database:
    container_name: database
    image: postgres:16.3
    ports:
      - "15432:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    env_file:
      - ../.env
    restart: always